#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CouncilorITC")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertZone(Zone instance);
  partial void UpdateZone(Zone instance);
  partial void DeleteZone(Zone instance);
  partial void InsertCouncilorName(CouncilorName instance);
  partial void UpdateCouncilorName(CouncilorName instance);
  partial void DeleteCouncilorName(CouncilorName instance);
  partial void InsertCouncilorType(CouncilorType instance);
  partial void UpdateCouncilorType(CouncilorType instance);
  partial void DeleteCouncilorType(CouncilorType instance);
  partial void InsertSendName(SendName instance);
  partial void UpdateSendName(SendName instance);
  partial void DeleteSendName(SendName instance);
  partial void InsertCaseBase(CaseBase instance);
  partial void UpdateCaseBase(CaseBase instance);
  partial void DeleteCaseBase(CaseBase instance);
  partial void InsertJobTitle(JobTitle instance);
  partial void UpdateJobTitle(JobTitle instance);
  partial void DeleteJobTitle(JobTitle instance);
  partial void InsertMailConfig(MailConfig instance);
  partial void UpdateMailConfig(MailConfig instance);
  partial void DeleteMailConfig(MailConfig instance);
  partial void InsertMailLog(MailLog instance);
  partial void UpdateMailLog(MailLog instance);
  partial void DeleteMailLog(MailLog instance);
  partial void InsertUserLogin(UserLogin instance);
  partial void UpdateUserLogin(UserLogin instance);
  partial void DeleteUserLogin(UserLogin instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CouncilorCaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Zone> Zone
	{
		get
		{
			return this.GetTable<Zone>();
		}
	}
	
	public System.Data.Linq.Table<CouncilorName> CouncilorName
	{
		get
		{
			return this.GetTable<CouncilorName>();
		}
	}
	
	public System.Data.Linq.Table<CouncilorType> CouncilorType
	{
		get
		{
			return this.GetTable<CouncilorType>();
		}
	}
	
	public System.Data.Linq.Table<searchCase> searchCase
	{
		get
		{
			return this.GetTable<searchCase>();
		}
	}
	
	public System.Data.Linq.Table<searchZone> searchZone
	{
		get
		{
			return this.GetTable<searchZone>();
		}
	}
	
	public System.Data.Linq.Table<searchCouncilorName> searchCouncilorName
	{
		get
		{
			return this.GetTable<searchCouncilorName>();
		}
	}
	
	public System.Data.Linq.Table<SendName> SendName
	{
		get
		{
			return this.GetTable<SendName>();
		}
	}
	
	public System.Data.Linq.Table<CaseBase> CaseBase
	{
		get
		{
			return this.GetTable<CaseBase>();
		}
	}
	
	public System.Data.Linq.Table<JobTitle> JobTitle
	{
		get
		{
			return this.GetTable<JobTitle>();
		}
	}
	
	public System.Data.Linq.Table<MailConfig> MailConfig
	{
		get
		{
			return this.GetTable<MailConfig>();
		}
	}
	
	public System.Data.Linq.Table<MailLog> MailLog
	{
		get
		{
			return this.GetTable<MailLog>();
		}
	}
	
	public System.Data.Linq.Table<UserLogin> UserLogin
	{
		get
		{
			return this.GetTable<UserLogin>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zone")]
public partial class Zone : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ZoneID;
	
	private string _Name;
	
	private string _State;
	
	private System.Nullable<int> _ZoneOrder;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZoneIDChanging(int value);
    partial void OnZoneIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZoneOrderChanging(System.Nullable<int> value);
    partial void OnZoneOrderChanged();
    #endregion
	
	public Zone()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ZoneID
	{
		get
		{
			return this._ZoneID;
		}
		set
		{
			if ((this._ZoneID != value))
			{
				this.OnZoneIDChanging(value);
				this.SendPropertyChanging();
				this._ZoneID = value;
				this.SendPropertyChanged("ZoneID");
				this.OnZoneIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(30)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(5)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneOrder", DbType="Int")]
	public System.Nullable<int> ZoneOrder
	{
		get
		{
			return this._ZoneOrder;
		}
		set
		{
			if ((this._ZoneOrder != value))
			{
				this.OnZoneOrderChanging(value);
				this.SendPropertyChanging();
				this._ZoneOrder = value;
				this.SendPropertyChanged("ZoneOrder");
				this.OnZoneOrderChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CouncilorName")]
public partial class CouncilorName : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CouncilorNameID;
	
	private System.Nullable<int> _CouncilorTypeID;
	
	private string _Name;
	
	private string _State;
	
	private System.Nullable<int> _CouncilorNameOrder;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCouncilorNameIDChanging(int value);
    partial void OnCouncilorNameIDChanged();
    partial void OnCouncilorTypeIDChanging(System.Nullable<int> value);
    partial void OnCouncilorTypeIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCouncilorNameOrderChanging(System.Nullable<int> value);
    partial void OnCouncilorNameOrderChanged();
    #endregion
	
	public CouncilorName()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouncilorNameID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int CouncilorNameID
	{
		get
		{
			return this._CouncilorNameID;
		}
		set
		{
			if ((this._CouncilorNameID != value))
			{
				this.OnCouncilorNameIDChanging(value);
				this.SendPropertyChanging();
				this._CouncilorNameID = value;
				this.SendPropertyChanged("CouncilorNameID");
				this.OnCouncilorNameIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouncilorTypeID", DbType="Int")]
	public System.Nullable<int> CouncilorTypeID
	{
		get
		{
			return this._CouncilorTypeID;
		}
		set
		{
			if ((this._CouncilorTypeID != value))
			{
				this.OnCouncilorTypeIDChanging(value);
				this.SendPropertyChanging();
				this._CouncilorTypeID = value;
				this.SendPropertyChanged("CouncilorTypeID");
				this.OnCouncilorTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(60)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(5)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouncilorNameOrder", DbType="Int")]
	public System.Nullable<int> CouncilorNameOrder
	{
		get
		{
			return this._CouncilorNameOrder;
		}
		set
		{
			if ((this._CouncilorNameOrder != value))
			{
				this.OnCouncilorNameOrderChanging(value);
				this.SendPropertyChanging();
				this._CouncilorNameOrder = value;
				this.SendPropertyChanged("CouncilorNameOrder");
				this.OnCouncilorNameOrderChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CouncilorType")]
public partial class CouncilorType : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CouncilorTypeID;
	
	private string _Type;
	
	private string _State;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCouncilorTypeIDChanging(int value);
    partial void OnCouncilorTypeIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    #endregion
	
	public CouncilorType()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouncilorTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int CouncilorTypeID
	{
		get
		{
			return this._CouncilorTypeID;
		}
		set
		{
			if ((this._CouncilorTypeID != value))
			{
				this.OnCouncilorTypeIDChanging(value);
				this.SendPropertyChanging();
				this._CouncilorTypeID = value;
				this.SendPropertyChanged("CouncilorTypeID");
				this.OnCouncilorTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(20)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(5)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.searchCase")]
public partial class searchCase
{
	
	private System.Nullable<int> _CaseBase;
	
	private int _UserLoginID;
	
	public searchCase()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseBase", DbType="Int")]
	public System.Nullable<int> CaseBase
	{
		get
		{
			return this._CaseBase;
		}
		set
		{
			if ((this._CaseBase != value))
			{
				this._CaseBase = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLoginID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int UserLoginID
	{
		get
		{
			return this._UserLoginID;
		}
		set
		{
			if ((this._UserLoginID != value))
			{
				this._UserLoginID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.searchZone")]
public partial class searchZone
{
	
	private System.Nullable<int> _Zone;
	
	private int _ZoneID;
	
	public searchZone()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="Int")]
	public System.Nullable<int> Zone
	{
		get
		{
			return this._Zone;
		}
		set
		{
			if ((this._Zone != value))
			{
				this._Zone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int ZoneID
	{
		get
		{
			return this._ZoneID;
		}
		set
		{
			if ((this._ZoneID != value))
			{
				this._ZoneID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.searchCouncilorName")]
public partial class searchCouncilorName
{
	
	private System.Nullable<int> _CouncilorName;
	
	private int _CouncilorNameID;
	
	public searchCouncilorName()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouncilorName", DbType="Int")]
	public System.Nullable<int> CouncilorName
	{
		get
		{
			return this._CouncilorName;
		}
		set
		{
			if ((this._CouncilorName != value))
			{
				this._CouncilorName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouncilorNameID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int CouncilorNameID
	{
		get
		{
			return this._CouncilorNameID;
		}
		set
		{
			if ((this._CouncilorNameID != value))
			{
				this._CouncilorNameID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SendName")]
public partial class SendName : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _SendNameID;
	
	private System.Nullable<int> _UserLoginID;
	
	private string _Type;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSendNameIDChanging(int value);
    partial void OnSendNameIDChanged();
    partial void OnUserLoginIDChanging(System.Nullable<int> value);
    partial void OnUserLoginIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
	
	public SendName()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendNameID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int SendNameID
	{
		get
		{
			return this._SendNameID;
		}
		set
		{
			if ((this._SendNameID != value))
			{
				this.OnSendNameIDChanging(value);
				this.SendPropertyChanging();
				this._SendNameID = value;
				this.SendPropertyChanged("SendNameID");
				this.OnSendNameIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLoginID", DbType="Int")]
	public System.Nullable<int> UserLoginID
	{
		get
		{
			return this._UserLoginID;
		}
		set
		{
			if ((this._UserLoginID != value))
			{
				this.OnUserLoginIDChanging(value);
				this.SendPropertyChanging();
				this._UserLoginID = value;
				this.SendPropertyChanged("UserLoginID");
				this.OnUserLoginIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(10)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaseBase")]
public partial class CaseBase : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CaseBaseID;
	
	private System.Nullable<int> _CouncilorNameID;
	
	private string _ContactName;
	
	private string _ContactTel;
	
	private System.Nullable<int> _ZoneID;
	
	private string _Address;
	
	private string _SuggestContent;
	
	private System.DateTime _SuggestDate;
	
	private string _ExecuteContent;
	
	private System.Nullable<int> _CaseOfficerID;
	
	private string _State;
	
	private System.Nullable<int> _AccessMap;
	
	private System.Nullable<System.DateTime> _ModifiedDate;
	
	private System.Nullable<System.DateTime> _EndDate;
	
	private System.Nullable<int> _EmployeeID;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCaseBaseIDChanging(int value);
    partial void OnCaseBaseIDChanged();
    partial void OnCouncilorNameIDChanging(System.Nullable<int> value);
    partial void OnCouncilorNameIDChanged();
    partial void OnContactNameChanging(string value);
    partial void OnContactNameChanged();
    partial void OnContactTelChanging(string value);
    partial void OnContactTelChanged();
    partial void OnZoneIDChanging(System.Nullable<int> value);
    partial void OnZoneIDChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnSuggestContentChanging(string value);
    partial void OnSuggestContentChanged();
    partial void OnSuggestDateChanging(System.DateTime value);
    partial void OnSuggestDateChanged();
    partial void OnExecuteContentChanging(string value);
    partial void OnExecuteContentChanged();
    partial void OnCaseOfficerIDChanging(System.Nullable<int> value);
    partial void OnCaseOfficerIDChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnAccessMapChanging(System.Nullable<int> value);
    partial void OnAccessMapChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnEmployeeIDChanging(System.Nullable<int> value);
    partial void OnEmployeeIDChanged();
    #endregion
	
	public CaseBase()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseBaseID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int CaseBaseID
	{
		get
		{
			return this._CaseBaseID;
		}
		set
		{
			if ((this._CaseBaseID != value))
			{
				this.OnCaseBaseIDChanging(value);
				this.SendPropertyChanging();
				this._CaseBaseID = value;
				this.SendPropertyChanged("CaseBaseID");
				this.OnCaseBaseIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouncilorNameID", DbType="Int")]
	public System.Nullable<int> CouncilorNameID
	{
		get
		{
			return this._CouncilorNameID;
		}
		set
		{
			if ((this._CouncilorNameID != value))
			{
				this.OnCouncilorNameIDChanging(value);
				this.SendPropertyChanging();
				this._CouncilorNameID = value;
				this.SendPropertyChanged("CouncilorNameID");
				this.OnCouncilorNameIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="NVarChar(60)")]
	public string ContactName
	{
		get
		{
			return this._ContactName;
		}
		set
		{
			if ((this._ContactName != value))
			{
				this.OnContactNameChanging(value);
				this.SendPropertyChanging();
				this._ContactName = value;
				this.SendPropertyChanged("ContactName");
				this.OnContactNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactTel", DbType="VarChar(60)")]
	public string ContactTel
	{
		get
		{
			return this._ContactTel;
		}
		set
		{
			if ((this._ContactTel != value))
			{
				this.OnContactTelChanging(value);
				this.SendPropertyChanging();
				this._ContactTel = value;
				this.SendPropertyChanged("ContactTel");
				this.OnContactTelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneID", DbType="Int")]
	public System.Nullable<int> ZoneID
	{
		get
		{
			return this._ZoneID;
		}
		set
		{
			if ((this._ZoneID != value))
			{
				this.OnZoneIDChanging(value);
				this.SendPropertyChanging();
				this._ZoneID = value;
				this.SendPropertyChanged("ZoneID");
				this.OnZoneIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(100)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuggestContent", DbType="NVarChar(600)")]
	public string SuggestContent
	{
		get
		{
			return this._SuggestContent;
		}
		set
		{
			if ((this._SuggestContent != value))
			{
				this.OnSuggestContentChanging(value);
				this.SendPropertyChanging();
				this._SuggestContent = value;
				this.SendPropertyChanged("SuggestContent");
				this.OnSuggestContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuggestDate", DbType="DateTime")]
	public System.DateTime SuggestDate
	{
		get
		{
			return this._SuggestDate;
		}
		set
		{
			if ((this._SuggestDate != value))
			{
				this.OnSuggestDateChanging(value);
				this.SendPropertyChanging();
				this._SuggestDate = value;
				this.SendPropertyChanged("SuggestDate");
				this.OnSuggestDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecuteContent", DbType="NVarChar(600)")]
	public string ExecuteContent
	{
		get
		{
			return this._ExecuteContent;
		}
		set
		{
			if ((this._ExecuteContent != value))
			{
				this.OnExecuteContentChanging(value);
				this.SendPropertyChanging();
				this._ExecuteContent = value;
				this.SendPropertyChanged("ExecuteContent");
				this.OnExecuteContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseOfficerID", DbType="Int")]
	public System.Nullable<int> CaseOfficerID
	{
		get
		{
			return this._CaseOfficerID;
		}
		set
		{
			if ((this._CaseOfficerID != value))
			{
				this.OnCaseOfficerIDChanging(value);
				this.SendPropertyChanging();
				this._CaseOfficerID = value;
				this.SendPropertyChanged("CaseOfficerID");
				this.OnCaseOfficerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(6)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessMap", DbType="Int")]
	public System.Nullable<int> AccessMap
	{
		get
		{
			return this._AccessMap;
		}
		set
		{
			if ((this._AccessMap != value))
			{
				this.OnAccessMapChanging(value);
				this.SendPropertyChanging();
				this._AccessMap = value;
				this.SendPropertyChanged("AccessMap");
				this.OnAccessMapChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifiedDate
	{
		get
		{
			return this._ModifiedDate;
		}
		set
		{
			if ((this._ModifiedDate != value))
			{
				this.OnModifiedDateChanging(value);
				this.SendPropertyChanging();
				this._ModifiedDate = value;
				this.SendPropertyChanged("ModifiedDate");
				this.OnModifiedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EndDate
	{
		get
		{
			return this._EndDate;
		}
		set
		{
			if ((this._EndDate != value))
			{
				this.OnEndDateChanging(value);
				this.SendPropertyChanging();
				this._EndDate = value;
				this.SendPropertyChanged("EndDate");
				this.OnEndDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int")]
	public System.Nullable<int> EmployeeID
	{
		get
		{
			return this._EmployeeID;
		}
		set
		{
			if ((this._EmployeeID != value))
			{
				this.OnEmployeeIDChanging(value);
				this.SendPropertyChanging();
				this._EmployeeID = value;
				this.SendPropertyChanged("EmployeeID");
				this.OnEmployeeIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobTitle")]
public partial class JobTitle : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _JobTitleID;
	
	private string _Name;
	
	private string _State;
	
	private System.Nullable<int> _JobTitleOrder;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobTitleIDChanging(int value);
    partial void OnJobTitleIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnJobTitleOrderChanging(System.Nullable<int> value);
    partial void OnJobTitleOrderChanged();
    #endregion
	
	public JobTitle()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int JobTitleID
	{
		get
		{
			return this._JobTitleID;
		}
		set
		{
			if ((this._JobTitleID != value))
			{
				this.OnJobTitleIDChanging(value);
				this.SendPropertyChanging();
				this._JobTitleID = value;
				this.SendPropertyChanged("JobTitleID");
				this.OnJobTitleIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(5)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleOrder", DbType="Int")]
	public System.Nullable<int> JobTitleOrder
	{
		get
		{
			return this._JobTitleOrder;
		}
		set
		{
			if ((this._JobTitleOrder != value))
			{
				this.OnJobTitleOrderChanging(value);
				this.SendPropertyChanging();
				this._JobTitleOrder = value;
				this.SendPropertyChanged("JobTitleOrder");
				this.OnJobTitleOrderChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MailConfig")]
public partial class MailConfig : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MailConfigID;
	
	private string _MailName;
	
	private string _SendName;
	
	private string _Subject;
	
	private string _Smtp;
	
	private System.Nullable<int> _Port;
	
	private string _MailID;
	
	private string _Password;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMailConfigIDChanging(int value);
    partial void OnMailConfigIDChanged();
    partial void OnMailNameChanging(string value);
    partial void OnMailNameChanged();
    partial void OnSendNameChanging(string value);
    partial void OnSendNameChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnSmtpChanging(string value);
    partial void OnSmtpChanged();
    partial void OnPortChanging(System.Nullable<int> value);
    partial void OnPortChanged();
    partial void OnMailIDChanging(string value);
    partial void OnMailIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
	
	public MailConfig()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailConfigID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MailConfigID
	{
		get
		{
			return this._MailConfigID;
		}
		set
		{
			if ((this._MailConfigID != value))
			{
				this.OnMailConfigIDChanging(value);
				this.SendPropertyChanging();
				this._MailConfigID = value;
				this.SendPropertyChanged("MailConfigID");
				this.OnMailConfigIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailName", DbType="NVarChar(50)")]
	public string MailName
	{
		get
		{
			return this._MailName;
		}
		set
		{
			if ((this._MailName != value))
			{
				this.OnMailNameChanging(value);
				this.SendPropertyChanging();
				this._MailName = value;
				this.SendPropertyChanged("MailName");
				this.OnMailNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendName", DbType="VarChar(50)")]
	public string SendName
	{
		get
		{
			return this._SendName;
		}
		set
		{
			if ((this._SendName != value))
			{
				this.OnSendNameChanging(value);
				this.SendPropertyChanging();
				this._SendName = value;
				this.SendPropertyChanged("SendName");
				this.OnSendNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(250)")]
	public string Subject
	{
		get
		{
			return this._Subject;
		}
		set
		{
			if ((this._Subject != value))
			{
				this.OnSubjectChanging(value);
				this.SendPropertyChanging();
				this._Subject = value;
				this.SendPropertyChanged("Subject");
				this.OnSubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Smtp", DbType="VarChar(50)")]
	public string Smtp
	{
		get
		{
			return this._Smtp;
		}
		set
		{
			if ((this._Smtp != value))
			{
				this.OnSmtpChanging(value);
				this.SendPropertyChanging();
				this._Smtp = value;
				this.SendPropertyChanged("Smtp");
				this.OnSmtpChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="Int")]
	public System.Nullable<int> Port
	{
		get
		{
			return this._Port;
		}
		set
		{
			if ((this._Port != value))
			{
				this.OnPortChanging(value);
				this.SendPropertyChanging();
				this._Port = value;
				this.SendPropertyChanged("Port");
				this.OnPortChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailID", DbType="VarChar(100)")]
	public string MailID
	{
		get
		{
			return this._MailID;
		}
		set
		{
			if ((this._MailID != value))
			{
				this.OnMailIDChanging(value);
				this.SendPropertyChanging();
				this._MailID = value;
				this.SendPropertyChanged("MailID");
				this.OnMailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MailLog")]
public partial class MailLog : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MailLogID;
	
	private string _Type;
	
	private string _SendTo;
	
	private string _SendContent;
	
	private string _SendMessage;
	
	private System.Nullable<System.DateTime> _SendDate;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMailLogIDChanging(int value);
    partial void OnMailLogIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnSendToChanging(string value);
    partial void OnSendToChanged();
    partial void OnSendContentChanging(string value);
    partial void OnSendContentChanged();
    partial void OnSendMessageChanging(string value);
    partial void OnSendMessageChanged();
    partial void OnSendDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSendDateChanged();
    #endregion
	
	public MailLog()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailLogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MailLogID
	{
		get
		{
			return this._MailLogID;
		}
		set
		{
			if ((this._MailLogID != value))
			{
				this.OnMailLogIDChanging(value);
				this.SendPropertyChanging();
				this._MailLogID = value;
				this.SendPropertyChanged("MailLogID");
				this.OnMailLogIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendTo", DbType="NVarChar(MAX)")]
	public string SendTo
	{
		get
		{
			return this._SendTo;
		}
		set
		{
			if ((this._SendTo != value))
			{
				this.OnSendToChanging(value);
				this.SendPropertyChanging();
				this._SendTo = value;
				this.SendPropertyChanged("SendTo");
				this.OnSendToChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendContent", DbType="NVarChar(MAX)")]
	public string SendContent
	{
		get
		{
			return this._SendContent;
		}
		set
		{
			if ((this._SendContent != value))
			{
				this.OnSendContentChanging(value);
				this.SendPropertyChanging();
				this._SendContent = value;
				this.SendPropertyChanged("SendContent");
				this.OnSendContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendMessage", DbType="NVarChar(MAX)")]
	public string SendMessage
	{
		get
		{
			return this._SendMessage;
		}
		set
		{
			if ((this._SendMessage != value))
			{
				this.OnSendMessageChanging(value);
				this.SendPropertyChanging();
				this._SendMessage = value;
				this.SendPropertyChanged("SendMessage");
				this.OnSendMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> SendDate
	{
		get
		{
			return this._SendDate;
		}
		set
		{
			if ((this._SendDate != value))
			{
				this.OnSendDateChanging(value);
				this.SendPropertyChanging();
				this._SendDate = value;
				this.SendPropertyChanged("SendDate");
				this.OnSendDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserLogin")]
public partial class UserLogin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _UserLoginID;
	
	private string _UserID;
	
	private string _Password;
	
	private string _UserName;
	
	private System.Nullable<int> _JobTitleID;
	
	private System.Nullable<int> _Unit;
	
	private System.Nullable<System.DateTime> _ModifiedDate;
	
	private string _State;
	
	private System.Nullable<int> _UserOrder;
	
	private string _Admin;
	
	private string _Officer;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserLoginIDChanging(int value);
    partial void OnUserLoginIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnJobTitleIDChanging(System.Nullable<int> value);
    partial void OnJobTitleIDChanged();
    partial void OnUnitChanging(System.Nullable<int> value);
    partial void OnUnitChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnUserOrderChanging(System.Nullable<int> value);
    partial void OnUserOrderChanged();
    partial void OnAdminChanging(string value);
    partial void OnAdminChanged();
    partial void OnOfficerChanging(string value);
    partial void OnOfficerChanged();
    #endregion
	
	public UserLogin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLoginID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int UserLoginID
	{
		get
		{
			return this._UserLoginID;
		}
		set
		{
			if ((this._UserLoginID != value))
			{
				this.OnUserLoginIDChanging(value);
				this.SendPropertyChanging();
				this._UserLoginID = value;
				this.SendPropertyChanged("UserLoginID");
				this.OnUserLoginIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(60)")]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(60)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleID", DbType="Int")]
	public System.Nullable<int> JobTitleID
	{
		get
		{
			return this._JobTitleID;
		}
		set
		{
			if ((this._JobTitleID != value))
			{
				this.OnJobTitleIDChanging(value);
				this.SendPropertyChanging();
				this._JobTitleID = value;
				this.SendPropertyChanged("JobTitleID");
				this.OnJobTitleIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="Int")]
	public System.Nullable<int> Unit
	{
		get
		{
			return this._Unit;
		}
		set
		{
			if ((this._Unit != value))
			{
				this.OnUnitChanging(value);
				this.SendPropertyChanging();
				this._Unit = value;
				this.SendPropertyChanged("Unit");
				this.OnUnitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ModifiedDate
	{
		get
		{
			return this._ModifiedDate;
		}
		set
		{
			if ((this._ModifiedDate != value))
			{
				this.OnModifiedDateChanging(value);
				this.SendPropertyChanging();
				this._ModifiedDate = value;
				this.SendPropertyChanged("ModifiedDate");
				this.OnModifiedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(5)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserOrder", DbType="Int")]
	public System.Nullable<int> UserOrder
	{
		get
		{
			return this._UserOrder;
		}
		set
		{
			if ((this._UserOrder != value))
			{
				this.OnUserOrderChanging(value);
				this.SendPropertyChanging();
				this._UserOrder = value;
				this.SendPropertyChanged("UserOrder");
				this.OnUserOrderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin", DbType="VarChar(5)")]
	public string Admin
	{
		get
		{
			return this._Admin;
		}
		set
		{
			if ((this._Admin != value))
			{
				this.OnAdminChanging(value);
				this.SendPropertyChanging();
				this._Admin = value;
				this.SendPropertyChanged("Admin");
				this.OnAdminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Officer", DbType="VarChar(5)")]
	public string Officer
	{
		get
		{
			return this._Officer;
		}
		set
		{
			if ((this._Officer != value))
			{
				this.OnOfficerChanging(value);
				this.SendPropertyChanging();
				this._Officer = value;
				this.SendPropertyChanged("Officer");
				this.OnOfficerChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
